In [9]:
#Vector_operation
import numpy as np
arr1=np.array([20,40,50,70,10])
arr2=np.array([2,3,4,5,6])
print(arr1)
print(arr2)
print(arr1+arr2)

[20 40 50 70 10]
[2 3 4 5 6]
[22 43 54 75 16]


In [10]:
#multiplication
print(arr1*arr2)

[ 40 120 200 350  60]


In [11]:
#subration
print(arr1-arr2)

[18 37 46 65  4]


In [12]:
#divisin
print(arr1/arr2)

[10.         13.33333333 12.5        14.          1.66666667]


In [19]:
#DOTproduct
print(arr1.dot(arr2))
sclr=3
print("scalar value:",sclr)
print("Array:",arr1)
print("Result:",arr1*sclr)

770
scalar value: 3
Array: [20 40 50 70 10]
Result: [ 60 120 150 210  30]


In [21]:
def my_func(x,y):
    if  x>y:
        return x-y
    else:
        return x+y
    arr1=np.array([20,0,50,70,10])
    arr2=np.array([2,3,4,5,6])
    vect_func=np.vectorize(my_func)
    print("array 1:",arr1)
    print("array 2:",arr2)
    print("result:",vect_func(arr1,arr2))