In [1]:
import numpy as np
a=np.array([10,20,30,40])
print("One dimentional array:",a)

One dimentional array: [10 20 30 40]


In [2]:
import numpy as np
b=np.array([[10,20,30,40],[50,60,70,80]])
print("two dimentional array:",b)

two dimentional array: [[10 20 30 40]
 [50 60 70 80]]


In [3]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("threen dimentional array:",c)

threen dimentional array: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [4]:
import numpy as np
d=np.zeros((3,5))
print("\n arrary with all zeros:\n",d)


 arrary with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
e=np.random.random((4,5))
print("\n random value:\n",e)


 random value:
 [[0.45605227 0.58745077 0.17437553 0.60744015 0.62161791]
 [0.43938716 0.88532361 0.67435032 0.89411278 0.17207643]
 [0.98438829 0.45364909 0.03098065 0.02506514 0.21652936]
 [0.48264368 0.34619549 0.76917362 0.6046567  0.07313531]]


In [10]:
import numpy as np
f=np.arange(0,6,7)
print("\n sequence array\n",f)


 sequence array
 [0]


In [12]:
import numpy as np
g=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarray=c.reshape(4,3)
print("\n three dimensional array:",g)
print("\n reshaped array:\n",newarray)


 three dimensional array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
h=arr.flatten()
print("\n three dimensional array:\n",arr)
print("\n flatten array:\n",h)


 three dimensional array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)


[1. 2. 3.]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::-1]
print(slice)

[9 8 7 6 5 4 3 2 1]


In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:3,1:3]
print(substring)

[[2 3]
 [5 6]
 [8 9]]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[2:6]
print(slice)

[3 4 5 6]


In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:3,1:3]
print("substring:\n",substring)
column1=arr[:,0]
print("columslicing:\n",column1)

substring:
 [[2 3]
 [5 6]
 [8 9]]
columslicing:
 [1 4 7]


In [19]:
import numpy as np
row1=arr[0,:]
print("rowslicing:\n",row1)

rowslicing:
 [1 2 3]


In [2]:
import numpy as np
import array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:4])

[[4 5 6]
 [7 8 9]]


In [1]:
import numpy as np
import array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:4])

[[4 5 6]
 [7 8 9]]
